### ISSUE TITLE
Failure to go get

### ISSUE THREAD

**Issue by chuckprice** [zeromq/goczmq#112]
Hi folks,

I'm seeing this when I go get this package:

$ go get github.com/zeromq/goczmq
# github.com/zeromq/goczmq
could not determine kind of name for C.zsock_destroy_checked
could not determine kind of name for C.zsock_new_checked

I'm sure I'm doing something wrong, but have no idea where to begin to track the problem.

Here's my go version:
$ go version
go version go1.4.2 linux/amd64

Thanks!

-chuck

**Comment by PSG-Luna** [comment]
Do you have czmq installed on your system and are the headers somewhere pkg-config can find ?

**Comment by chuckprice** [comment]
Yes and yes. -chuck

**Comment by chuckprice** [comment]
Sorry for the previous brief response, I was mobile (but not texting and driving!).

The czmq headers are in /usr/include. sodium, zmq, and czmq are installed and being used by a c++ program on the same system, if that helps. They were built using gcc.

**Comment by chuckprice** [comment]
I should also note that my system is running gcc-4.7 . I've seen some net chatter regarding issues with various versions of gcc. Could this be a problem?

**Comment by chuckprice** [comment]
Ok I will close this. I've not been able to reproduce it on another machine, built up from scratch by me. (The other machine was built up by one of my team members at my direction, but I can't validate that the instructions were followed to the letter, so I'll assume this is our own cockpit error.)

**Comment by taotetek** [comment]
Ok Chuck - if you run into it again, just let us know!

Brian
