### ISSUE TITLE
Building on windows

### ISSUE THREAD

**Issue by vrecan** [zeromq/goczmq#137]
I am working on a project that requires zeromq on windows and linux. I've got libsodium, zeromq and czmq building for windows. When I go get goczmq I get this error:
```
$ go get github.com/zeromq/goczmq
# pkg-config --cflags libczmq libzmq libsodium
pkg-config: exec: "pkg-config": executable file not found in %PATH%
```
Why does it require pkg-config to build? I should mention I am cross compiling all the libs for libsodium, zeromq and czmq. Previously this all worked with zmq4 without czmq. 

I tried to install pkg-config but it then complains about libglib-2.0 which I am sure isn't the last dependency. pkg-config looks really hard to build for windows.

**Comment by taotetek** [comment]
Currently we're using pkg-config to handle finding the build deps - see:

https://github.com/zeromq/goczmq/blob/master/goczmq.go#L9

If there's another way to handle this with cgo that would work on windows
without requiring pkg-config I'm all ears - I just personally don't work
with windows nor do I have a test environment for windows.


Brian
