### ISSUE TITLE
Problem: Poller constructor requires at least one socket.

### ISSUE THREAD

**Issue by ggitau** [zeromq/goczmq#141]
Is there a way I can create a poller and not have to add a reader/socket when creating it?With the native implementation, I usually pass NULL to zpoller_new then call zpoller_add later.

**Comment by taotetek** [comment]
@ggitau if I'm remembering correctly, the only thing that keeps you from doing this is a check that throws an error if your arg length is 0 - I believe I could just remove this check and have it create an empty poller that you could then add sockets to.  I'll send a PR with a test to ensure this works.

**Comment by taotetek** [comment]
Fixed - https://github.com/zeromq/goczmq/pull/142
