### ISSUE TITLE
Sock.RecvFrame() crashes w/ sigabrt if called after Sock.Destroy()

### ISSUE THREAD

**Issue by jordansissel** [zeromq/goczmq#148]
Background: Similar problem likely to https://github.com/zeromq/goczmq/issues/145

This probably also affects RecvMessage, SendFrame, and SendMessage, but I haven't checked.

@PSG-Luna You had concerns about using panic(), and I think I agree with you. Any thoughts on the type of error? I was thinking something like:

```go
type SocketIsDestroyed struct {}

func (e *SocketIsDestroyed) Error() string {
  return "Socket was destroyed, it cannot be used anymore."
}
```

Thoughts? I can provide patches.

**Comment by taotetek** [comment]
@jordansissel Hello!  sorry for the slow response, I was on vacation :)  So, what we have here is a series of cases where making a call against a CZMQ "class" (like a socket or a proxy) after Destroy() is called will trigger an issue.

My brain isn't quite back from vacation yet - but it looks like the options we're discussiong are:

a) a check for whether Destroy() has been called, followed by a panic at the go layer (to head off the underlying assert failure in the C API, or

b) Returning an error for calls that already return an error and can hit this edge case, which looks like what you are proposing above.

In cases where a call already returns an error as part of it's signature, so we don't have to break the API to make the change, I prefer b, and it looks like that's what @PSG-Luna prefers as well.

If you'd like to send a PR, go for it!

**Comment by jordansissel** [comment]
Ok I'll work on a patch as time permits. I am in favor of option `b` as well!

@PSG-Luna can you confirm that using errors instead of panics will resolve with your concerns?

**Comment by taotetek** [comment]
Oops, this was fixed by @indradhanush !
