### ISSUE TITLE
Beacon.Recv returns a string, but Beacons are 2 frames

### ISSUE THREAD

**Issue by jordansissel** [zeromq/goczmq#151]
Sample code: https://gist.github.com/jordansissel/3ad77aab81ca92f898a7

The Recv method returns a single string value, but each Beacon appears to be two frames - the IP and the announcement string.

Example, running `./beacon one` and `./beacon two`:

```
INFO[0000] New beacon running                            announcement=one
INFO[0001] Received beacon                               announcement=one str=192.168.1.135
INFO[0001] Received beacon                               announcement=one str=two
INFO[0003] Received beacon                               announcement=one str=192.168.1.135
INFO[0003] Received beacon                               announcement=one str=two
```

Each beacon requires basically 2 Recv() calls because under the hood it invokes zstr_recv. The docs for zbeacon say this:

```
//  Receive next beacon from a peer. Received beacons are always a 2-frame
//  message containing the ipaddress of the sender, and then the binary
//  beacon data as published by the sender:
//
//      zmsg_t *msg = zmsg_recv (beacon);
```

I think this means two things:

1) API change: Beacon.Recv() should return two values: a string (the IP) and a []byte (the announcement)
2) Internals change: we should call whatever method (zmsg_recv?) that will get us both frames from the request.

Thoughts?

**Comment by taotetek** [comment]
@jordansissel Nice catch!  In cases where we receive multi-part messages in other parts of the api, we usually return [][]byte ( see: https://github.com/zeromq/goczmq/blob/master/sock.go#L314 ).

So maybe we could a) change Beacon.Recv() to return a [][]byte, and modify the internals to handle getting both message frames correctly?

**Comment by taotetek** [comment]
@jordansissel Change is in, Beacon Recv now returns [][]byte, with first []byte containing address and second []byte containing the beacon message.  Let me know if this works for you, and if it does I'll close the issue.

Thanks as always for the feedback!

**Comment by jordansissel** [comment]
@taotetek Looks good to me! <3 for getting to the patch before I could :)

**Comment by taotetek** [comment]
@jordansissel you're welcome! <3
