### ISSUE TITLE
Cross platform builds for Windows and Linux fail from OS X build

### ISSUE THREAD

**Issue by rgbkrk** [zeromq/goczmq#165]
I'm trying to build a statically built binary to run across all the major platforms, but this isn't working with Windows or Linux (built from my OS X machine).
## Windows

```
$ CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -a -tags netgo -ldflags '-w' -o client .
# github.com/zeromq/goczmq
warning: unknown warning option '-Wno-pedantic-ms-format'; did you mean '-Wno-pedantic'? [-Wunknown-warning-option]
../../../../../zeromq/goczmq/auth.go:4:10: fatal error: 'czmq.h' file not found
#include "czmq.h"
         ^
1 warning and 1 error generated.
```
## Linux

```
$ CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w' -o client .
# runtime/cgo
ld: unknown option: --build-id=none
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
## Darwin

```
$ CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -a -tags netgo -ldflags '-w' -o client .
$ # built fine
```
# Next steps

I'm going to try out the old way of doing this tomorrow (using Gimme to fetch the right versions of go), but it would cool to figure out if/where this can be addressed in goczmq to make cross platform builds work well.

**Comment by taotetek** [comment]
@rgbkrk Thanks for the issue report!  This would be a really nice thing to have.  While this is a bit outside my own use cases, and I only have a Linux build environment, I'm happy to help out and test potential solutions as I can.

**Comment by rgbkrk** [comment]
Admittedly, I just wanted this to work late at night. Cross compiling Golang is super easy - I'm continually shipping binaries across all arches and platforms over Travis. The core limitation is cross compiling C, which [used to be an issue in the standard library for golang](https://inconshreveable.com/04-30-2014/cross-compiling-golang-programs-with-native-libraries/) too.

**Comment by taotetek** [comment]
@rgbkrk "I want this to be easy to do late at night when I'm sleep deprived" is a valid problem statement ;)

**Comment by taotetek** [comment]
Closing this for now.

**Comment by rgbkrk** [comment]
Works for me, I'm happy in zeromq.js land for now. 😄
