### ISSUE TITLE
C.free() must be called to free the memory allocated by C.CString()

### ISSUE THREAD

**Issue by MoZhonghua** [zeromq/goczmq#181]
C.free() must be called to free the memory allocated by C.CString(), for example:
```go
func (a *Auth) Verbose() error {
	// Must call C.free()
	v := C.CString("VERBOSE")
	defer C.free(v)
	rc := C.zstr_send(unsafe.Pointer(a.zactorT), v)
	if rc == -1 {
		return ErrActorCmd
	}
	C.zsock_wait(unsafe.Pointer(a.zactorT))

	return nil
}
```

**Comment by taotetek** [comment]
@MoZhonghua Fixed - thanks for the bug report!

**Comment by MoZhonghua** [comment]
I think you should do:
```bash
find . -name '*.go' | xargs grep CString
```
and add C.free() for __EVERY__ C.CString(), not only the one use a literal, but also the ones using go string, for example:
```go
// NewGossip creates a new Gossip actor
func NewGossip(name string) *Gossip {
	g := &Gossip{}
	g.zactorT = C.Gossip_new(C.CString(name))  // memory leak
	return g
}
```
BTW: I think this may cause a performance penalty (one alloc and free for every single API call), a benchmark should be done for the API which is called very frequently.
