### ISSUE TITLE
Error "ZMQ_SUBSCRIBE is not valid on XSUB sockets" when creating NewXSubChanneler

### ISSUE THREAD

**Issue by tswast** [zeromq/goczmq#187]
I am not able to create a NewXSubChanneler. It seems like the subscription argument should not be here.

    package main
    
    import (
        "github.com/zeromq/goczmq"
        "log"
    )
    
    func main() {
        sub := goczmq.NewXSubChanneler("tcp://127.0.0.1:5000", "" /* empty subscription to get all messages */)
        defer sub.Destroy()
        for msg := range sub.RecvChan {
                log.Printf("Got message:\n\t%#v\n", msg)
        }       
    }

Running this gives the following output:

    % ./xsub 
    ZMQ_SUBSCRIBE is not valid on XSUB sockets
    xsub: src/zsock_option.c:906: zsock_set_subscribe: Assertion `0' failed.
    SIGABRT: abort
    PC=0x7f481b5ebcc9 m=0
    signal arrived during cgo execution
    
    goroutine 6 [syscall, locked to thread]:
    runtime.cgocall(0x4073b0, 0xc82004bd20, 0x0)
            /usr/lib/google-golang/src/runtime/cgocall.go:120 +0x11b fp=0xc82004bcf0 sp=0xc82004bcc0
    github.com/zeromq/goczmq._Cfunc_zsock_set_subscribe(0x8c07f0, 0x8c03f0)
            github.com/zeromq/goczmq/_obj/_cgo_gotypes.go:1563 +0x31 fp=0xc82004bd20 sp=0xc82004bcf0
    github.com/zeromq/goczmq.(*Sock).SetSubscribe(0xc82000e500, 0x0, 0x0)
            /usr/local/google/home/swast/gocode/src/github.com/zeromq/goczmq/sock_option.go:297 +0x46 fp=0xc82004bd40 sp=0xc82004bd20
    github.com/zeromq/goczmq.(*Channeler).actor(0xc8200120e0, 0xc820022180)
            /usr/local/google/home/swast/gocode/src/github.com/zeromq/goczmq/channeler.go:65 +0xb7a fp=0xc82004bfa0 sp=0xc82004bd40
    runtime.goexit()
            /usr/lib/google-golang/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82004bfa8 sp=0xc82004bfa0
    created by github.com/zeromq/goczmq.newChanneler
            /usr/local/google/home/swast/gocode/src/github.com/zeromq/goczmq/channeler.go:186 +0x419
    
    goroutine 1 [chan receive]:
    main.main()
            /usr/local/google/home/swast/gocode/src/github.com/tswast/xsub/main.go:11 +0xcf
    
    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
            /usr/lib/google-golang/src/runtime/asm_amd64.s:1696 +0x1
    
    goroutine 5 [select]:
    github.com/zeromq/goczmq.(*Channeler).channeler(0xc8200120e0, 0xc8200220c0, 0xc820022120)
            /usr/local/google/home/swast/gocode/src/github.com/zeromq/goczmq/channeler.go:140 +0x527
    created by github.com/zeromq/goczmq.newChanneler
            /usr/local/google/home/swast/gocode/src/github.com/zeromq/goczmq/channeler.go:185 +0x3ed
    
    rax    0x0
    rbx    0x7f481c04d000
    rcx    0xffffffffffffffff
    rdx    0x6
    rdi    0x37e6
    rsi    0x37e6
    rbp    0x7f481b735830
    rsp    0x7ffe3b08f0a8
    r8     0xfefefefefefefe00
    r9     0x8c0410
    r10    0x8
    r11    0x202
    r12    0x7f481bc2189e
    r13    0x7f481bc20e60
    r14    0x3
    r15    0x8
    rip    0x7f481b5ebcc9
    rflags 0x202
    cs     0x33
    fs     0x0
    gs     0x0

It works fine if I remove the X and just create a NewSubChanneler.

**Comment by taotetek** [comment]
@tswast - Thanks for the report and test case!  Will try to set aside some time in the next day or two to take a look at this and get it fixed!

**Comment by taotetek** [comment]
@tswast - XSub does not accept subscription options as XSub's purpose is to get all subscriptions - my bad - have fixed in this PR - https://github.com/zeromq/goczmq/pull/188
