### ISSUE TITLE
gossip recv missing

### ISSUE THREAD

**Issue by monotrememan42** [zeromq/goczmq#190]
there is no receive/consume analog of gossip.Publish.
that is, you can set a key/value pair but there is no way to see it,
or all of them. the simplest answer would be something like
func (*Gossip) Status() map[string]string
which would return a map of all known k/v pairs.
For extra marks, i would add a way for the app to get new k/v pairs as they publish,
either as a chan of struct { string, string }, or registering a callback function.

**Comment by monotrememan42** [comment]
be warned that eventually they will implement deleting k/v pairs, so if you do the event channel, do triples like ("add"|"delete", key [, value]). likewise, the callback should take an operator parameter.

**Comment by taotetek** [comment]
Just a heads up that we're removing the gossip API wrapper - see https://github.com/zeromq/goczmq/pull/195 for details.  If  someone has a strong need for it, we'd gladly accept a pull request but currently it was not serving a need.
