### ISSUE TITLE
Problem: I want to make backwards incompatible changes.

### ISSUE THREAD

**Issue by taotetek** [zeromq/goczmq#196]
I would like to start adding support for the new thread safe sockets to goczmq:
- ZMQ_RADAR / ZMQ_DISH
- ZMQ_SCATTER / ZMQ_GATHER
- ZMQ_CLIENT  / ZMQ_SERVER

This would of course break building goczmq against the current stable release of libzmq and czmq.

I am thinking about using gopkg.in ( http://labix.org/gopkg.in ) to handle this, the same way oliver's elastic library does for dealing with multiple incompatible versions of the elasticsearch API ( see: https://github.com/olivere/elastic ).

I'm putting this issue here to solicit feedback and give a heads up.

**Comment by rgbkrk** [comment]
I'm a big fan of gopkg.in for delivering stable releases of a library (without making people track down specific commits for vendoring). Happy to switch my current code over to using a release on gopkg.in so goczmq can start making changes.

**Comment by PSG-Luna** [comment]
Switching to gopkg.in now would break people's code as they'd have to change an import. I think if the API changes aren't huge, just breaking the code is fine.

**Comment by taotetek** [comment]
@PSG-Luna unfortunately it does more than break the API - since golang does not support conditional compilation, no one would be able to build goczmq against anything other than a czmq older than yesterdays commits.

I want to add in the ability to use the new socket types while maintaining the ability for people to build without those socket types against the current stable libzmq and czmq releases.

**Comment by hintjens** [comment]
I'd like to abstract this in the CZMQ API so that all these socket types are supported, yet return a null if the underlying core doesn't support them. One idea I had was to add a zsock_new () with a string argument instead of a constant. I did not get around to trying this.

**Comment by taotetek** [comment]
@hintjens aha - that might be an interesting thing to try!

**Comment by taotetek** [comment]
I'm going to start a fork in my own repo with support for the  new socket types, and we'll figure out how to integrate it back in.  At the moment, I'll probably go with gopkg.in.  Down the road, @hintjens suggestion around not requiring the constants and allowing for a null check  on the socket sounds like something worth trying out.

**Comment by hintjens** [comment]
possibly a wrapper like zsock_news
