### ISSUE TITLE
Problem: RecvChan is not closed when router is destroyed

### ISSUE THREAD

**Issue by cyrilleverrier** [zeromq/goczmq#199]
1. my application is receiving messages in a go subroutine:
```
router := NewRouterChanneler("inproc://channelerouter")
resp := <-router.RecvChan
```

2. my application catches signal interrupt (Ctr-C) and wants to exit properly by closing/destroying resources:
```
router.Destroy()
```

Problem:
The go routine is still hanging, waiting for data on router.RecvChan

**Comment by taotetek** [comment]
Thanks  @cyrilleverrier ! I merged https://github.com/zeromq/goczmq/pull/200 .
