### ISSUE TITLE
could not determine kind of name for C.ZMQ_HWM

### ISSUE THREAD

**Issue by sheepbao** [zeromq/goczmq#213]
Hi all, I try to learn zmq from [zmq hello world](http://zguide.zeromq.org/go:hwserver)
and I try to build it,
but I get this error:
```
# github.com/alecthomas/gozmq
could not determine kind of name for C.ZMQ_HWM
could not determine kind of name for C.ZMQ_MCAST_LOOP
could not determine kind of name for C.ZMQ_RECOVERY_IVL_MSEC
could not determine kind of name for C.ZMQ_SWAP
```
My os is mac, and I have `brew install zmq czmq libsodium`.
my golang version `go version go1.7.1 darwin/amd64`
Please help! Thanks!

**Comment by rgbkrk** [comment]
Looks like the hello world server docs need an update now that this package exists. It's currently referencing https://github.com/alecthomas/gozmq, which @alecthomas has deprecated in favor of pebbe's or this one.

**Comment by sheepbao** [comment]
@rgbkrk Thank you reply!
