### ISSUE TITLE
Problem: goczmq uses deprecated CZMQ APIs

### ISSUE THREAD

**Issue by bluca** [zeromq/goczmq#217]
The CZMQ v2 APIs have been declared deprecated with the 3.0.0 release in October 2014: https://github.com/zeromq/czmq#toc3-8224

Following the C4.1 process we are moving toward retiring those APIs - i.e. deleting them. This will break goczmq.

The solution would be to update goczmq to use the new v3 APIs from CZMQ.

There are such API calls: zsocket_set_curve_secretkey_bin and zsocket_set_curve_publickey_bin

https://github.com/zeromq/goczmq/blob/master/cert.go#L94
https://github.com/zeromq/goczmq/blob/master/cert.go#L95

As far as I can see it should be a trivial change to use zsock_set_curve_secretkey_bin and zsock_set_curve_publickey_bin, the signature is the same but they take a zsock instead of a zsocket (and I believe goczmq already uses zsocks). I'd send a PR, but unfortunately I'm not a GO person so I can't be sure I won't break anything :-)

**Comment by taotetek** [comment]
@bluca thanks for the heads up! if i can't get to this this week can definitely get to it by next weekend.

**Comment by taotetek** [comment]
Fixed!
