### ISSUE TITLE
fix windows platform add  ZMQ_SCATTER / ZMQ_GATHER can't Compile

### ISSUE THREAD

**Issue by imkos** [zeromq/goczmq#224]
cgo windows CFLAGS: -Wno-pedantic-ms-format -DLIBCZMQ_EXPORTS -DZMQ_BUILD_DRAFT_API -DZMQ_DEFINED_STDINT -DLIBCZMQ_EXPORTS

add DZMQ_BUILD_DRAFT_API

**Comment by taotetek** [comment]
@imkos thanks for the issue report - I can get this fix in over the weekend when I'll be doing some goczmq work.
