### ISSUE TITLE
Security support in goczmq binding

### ISSUE THREAD

**Issue by jay11ca39** [zeromq/goczmq#235]
Hello @taotetek ,

I want to use zeroMQ for my project. My project is in go language. So, I want to use go binding for zeroMQ.

I got to know there are 2 go bindings available:
(a) https://github.com/zeromq/goczmq
(b) http://github.com/pebbe/zmq4
 
Source: http://zeromq.org/bindings:go

But I have a few questions:

Is security feature is fully supported in this binding?
Is there is any performance comparison between :
This binding and http://github.com/pebbe/zmq4 ?
It is a blocker for me, which one to choose.
can you please help me out in this.
Thanks in advance.

**Comment by taotetek** [comment]
@jay11ca39 Security is fully supported, yes. Performance is equivalent to pebbe/zmq4. If you want some of the API features of CZMQ, then goczmq is a great choice. If you want a closer direct translation of libzmq, then pebbe/zmq4 is great.
