### ISSUE TITLE
Unable to recover from panics when creating new Channeler

### ISSUE THREAD

**Issue by aldencolerain** [zeromq/goczmq#242]
Creating and destroying a listening Channeler on the same tcp port in rapid succession eventually triggers a panic "error attaching to zsock".  I'm assuming there isn't a way to wait and ensure Destroy has been completed, so I tried to attempt to create the Channeler continuously a until a timeout had been reached, but it looks like the panic is called from a go routine and therefore can't be recovered.

I wonder if these errors should be returned via an error channel rather than a total panic?

It would be also useful to know if there was a pattern to identify when the Channeler was totally destroyed and had released the socket.

**Comment by bendikro** [comment]
This behaviour is horrible. It's not possible to even log an error statement before it crashes.

**Comment by taotetek** [comment]
goczmq uses the C4 process for open source software development ( https://rfc.zeromq.org/spec:42/C4 ) and pull requests are welcome.
