### ISSUE TITLE
Build with CGO_ENABLED=0 does not work

### ISSUE THREAD

**Issue by daveamit** [zeromq/goczmq#245]
I am trying to build a static binary (To put in a docker image - from scratch). So, when I execute following
`env CGO_ENABLED=0 GOOS=linux go build -a -v -installsuffix cgo main.go` it fails with 
```
runtime/internal/sys
runtime/internal/atomic
runtime
errors
internal/race
sync/atomic
internal/cpu
unicode/utf8
unicode
math
sync
github.com/vmihailenco/msgpack/codes
io
syscall
bytes
strings
strconv
bufio
math/rand
reflect
time
internal/poll
os
fmt
sort
encoding/binary
github.com/vmihailenco/msgpack
github.com/zeromq/goczmq
go build github.com/zeromq/goczmq: build constraints exclude all Go files in /home/amit/go/src/github.com/zeromq/goczmq
```

Any help appreciated 

NOTE: If I use CGO_ENABLE=1, it works but when I launch docker image, it fails with "not found" error

Thanks !

**Comment by daveamit** [comment]
@taotetek, sorry to bother you, I understand you must be busy, but can you please point me to right direction ? I strongly believe I am missing something ...

**Comment by manveru** [comment]
That's because `goczmq` depends on the `czmq` C library and there's no pure Go alternative to that yet.

**Comment by daveamit** [comment]
Oh ... okay, thanks for the clarification ...
