### ISSUE TITLE
go.mod support invalid

### ISSUE THREAD

**Issue by sbinet** [zeromq/goczmq#259]
the `go.mod` file is inconsistent with the expected import path:

https://travis-ci.org/go-zeromq/zmq4/jobs/554152802

it reads `github.com/zeromq/goczmq` while it should be `gopkg.in/zeromq/goczmq.v4`.
this will break under Go-1.13.

**Comment by ankushchadha** [comment]
There is a stackoverflow thread about this - https://stackoverflow.com/questions/57355929/what-incompatible-in-go-mod-mean-will-it-make-harm/58244519#58244519

'/v4' suffix should be added to the module name. Without this change, consumers of this module version will also break once they adopt Go 1.13.
