### ISSUE TITLE
SetSndHwm removed?

### ISSUE THREAD

**Issue by ggggggggg** [zeromq/goczmq#260]
My CI tests are failing with an unexpected error "pubSocket.SetSndhwm undefined (type *goczmq.Sock has no field or method SetSndhwm)" as can be seen here: https://travis-ci.org/usnistgov/dastard/builds/557528595?utm_source=github_status&utm_medium=notification
I also can't find that function in the documentation anymore.

My tests still pass locally, so I'm wondering if this API was removed on purpose and I just have an out of date version locally?

**Comment by ggggggggg** [comment]
I'm guessing this has been gone for a while, and I just screwed up git and brought in some old code using old APIs. Closing.

**Comment by taotetek** [comment]
Hello! If you are pulling from *master* or the most current release there
is a breaking change on the master branch around socket options - the way
socket options work was moved from direct functions on the Sock type, to
optional functional arguments that you can pass to the constructor, or via
the SetOption API. Here's an example from the tests:

https://github.com/zeromq/goczmq/blob/master/sock_option_test.go#L319-L328

Here's the release:  https://github.com/zeromq/goczmq/releases/tag/v4.2.0

Here's the release that work was started in:
https://github.com/zeromq/goczmq/releases/tag/v4.1.0

Cheers,
Brian
