### ISSUE TITLE
gopkg.in/zeromq/goczmq.v4: cannot find module providing package gopkg.in/zeromq/goczmq.v4: gopkg.in/zeromq/goczmq.v4@v4.2.0: invalid version: go.mod has non-....v4 module path "github.com/zeromq/goczmq" at revision v4.2.0

### ISSUE THREAD

**Issue by natxo** [zeromq/goczmq#302]
go version go1.16.8 linux/amd64
OS: fedora 34
libraries:
    Install czmq-4.2.1-6.fc34.x86_64                @fedora
    Install czmq-devel-4.2.1-6.fc34.x86_64          @fedora
    Install keyutils-libs-devel-1.6.1-2.fc34.x86_64 @fedora
    Install libcom_err-devel-1.45.6-5.fc34.x86_64   @fedora
    Install libsodium-devel-1.0.18-7.fc34.x86_64    @fedora
    Install libunwind-devel-1.4.0-5.fc34.x86_64     @fedora
    Install libuuid-devel-2.36.2-1.fc34.x86_64      @fedora
    Install libverto-devel-0.3.2-1.fc34.x86_64      @fedora
    Install openpgm-5.2.122-26.fc34.x86_64          @fedora
    Install openpgm-devel-5.2.122-26.fc34.x86_64    @fedora
    Install zeromq-4.3.4-1.fc34.x86_64              @fedora
    Install zeromq-devel-4.3.4-1.fc34.x86_64        @fedora
    Install krb5-devel-1.19.2-2.fc34.x86_64         @updates

```
package main

import (
	"fmt"
	"gopkg.in/zeromq/goczmq.v4"
)

func main() {
	fmt.Println("vim-go")
	dealer, err := gozmq.NewDealer("tcp://salt.l.example.org:4505")
	if err != nil {
		panic(err)
	}
	defer dealer.Destroy()
}
```
When running go tidy I get the error on the subjet line:
$ go mod tidy
go: finding module for package gopkg.in/zeromq/goczmq.v4
xx imports
	gopkg.in/zeromq/goczmq.v4: cannot find module providing package gopkg.in/zeromq/goczmq.v4: gopkg.in/zeromq/goczmq.v4@v4.2.0: invalid version: go.mod has non-....v4 module path "github.com/zeromq/goczmq" at revision v4.2.0

Any ideas what I am doing wrong?
Thanks!

**Comment by joefowler** [comment]
Hi @natxo. I have the same problem. I think this is what's being described in #279, with excellent explanation and route to fixing it. I don't really understand it, but it sounds like this package hasn't kept up with the latest Golang module standards.

Perhaps suggestion 5 by @KateGo520 in #279 will help you?

**Comment by natxo** [comment]
thanks! I tried with the github.com/pebbe/zmq4 library, and it works, so I guess that is also another option.

**Comment by joefowler** [comment]
@natxo: I have tried the zmq4 library, too. I like it (skipping straight over `czmq` to the `zmqlib` seems like a good idea). We had performance troubles when we were using it. I think we were too quick to blame zmq4 itself, when the fault was probably ours.

I might try it again, because it looks like this package (`goczmq`) is not very active, and I'm having a hard crash somewhere in this, or in czmq, that I can't diagnose.
