### ISSUE TITLE
Combining Attach on the bind side with a Connect on the connect side fails over inproc on Dealer/Pair sockets

### ISSUE THREAD

**Issue by PSG-Luna** [zeromq/goczmq#60]
As per title, I have not tested other socket combinations or non inproc

**Comment by taotetek** [comment]
@PSG-Luna do we know if this is still an issue?  Was this due to our initial confusion over @ vs > because of conflicting comments?

**Comment by PSG-Luna** [comment]
This can be closed, indeed
