### ISSUE TITLE
Undefined behavior with cgo

### ISSUE THREAD

**Issue by PSG-Luna** [zeromq/goczmq#76]
Currently, we sometimes directly pass pointers of go objects to C land.
The behaviour of this code happens to work, but is currently not well defined and will change with later go versions.
I propose we start getting rid of these already so we have less work when the next version of go is released (in 6 months from now) that will include a moving garbage collector.

Example: https://github.com/zeromq/goczmq/blob/master/sock.go#L332

**Comment by taotetek** [comment]
I agree we should get out ahead of this.  We have perf tests so we can assess how much doing it "right" makes us sad when we make the changes.

**Comment by taotetek** [comment]
Going to close this for now as a problem we don't have yet.
