### ISSUE TITLE
Problem: No Nice Consistent Way For Dealing Wth Bytes and Strings

### ISSUE THREAD

**Issue by taotetek** [zeromq/goczmq#82]
Overview:

* RecvBytes returns a []byte, flag, error
* RecvString returns string, error and no flag

These are inconsistent, and RecvString should return a more flag to be usable with multi part messages.

* RecvMessage returns a full message as [][]bytes (and an error)
* RecvMultiString returns a full message as a []string and an error

These are  consistent, but the names are not so wonderful.

* Channeler returns a channel of [][]byte messages, which is great - but any person who would like to get []string back from Channeler will need to write a little code - yesterday we discussed that we could make some utility functions for transposing between [][]byte <-> []string when working with Channeler.

Thoughts:

* The utility functions for working with Channeler won't break anything, they are additions.
* RecvMessage / RecvMultiString should be named something more consistent, like RecvBytesMessage / RecvStringsMessage (I probably am bad at naming things).  This is a breaking change so we should discuss
* RecvString should be changed to return string, flag, err like RecvBytes.  This is a breaking change so we shold discuss

Thoughts from others welcome, this is just my early morning coffee thoughts on this.

**Comment by PSG-Luna** [comment]
How does C string formatting differ from Go string formatting ? Is doing a plain string(stuff) not enough to convert the []byte to a string ? Is a special goczmq function actually needed ?

**Comment by taotetek** [comment]
@PSG-Luna string() works fine for a []byte that has been returned from a zeromq socket even if zstr_send was used from the C side to send it.  Same on the send side - e.g., if you send a bunch of bytes from goczmq, and receive them from czmq using zstr_recv, zstr_recv will just append a null byte on the end assuming you know what you want.

So nothing special on our end at all.

**Comment by PSG-Luna** [comment]
In that case I'd (personally) remove all the string related methods and let the caller just call string() if that's what they want. That might be a bit too radical though.

**Comment by taotetek** [comment]
@PSG-Luna The string methods were added, because I felt like they "should" exist.  I'm not actually using RecvMultiString or RecvString for anything.  This suggests that perhaps these methods are not solving a real problem, but rather a hypothetical problem.  I could:

* remove RecvString
* remove RecvMultiString
*  fix the two non directly related tests that this would break

This sets the expactation that goczmq always works with bytes, and assumes that people can deal with bytes -> strings themselves, which seems a reasonable assumption.  The various io interfaces in go deal with bytes after all.

Then, if someone comes up with a problem based on an actual implementation, where a utility method of some sort would be useful, it could be submitted as a pull request that solves a real world problem.

I'm ok with this.

**Comment by PSG-Luna** [comment]
I'm OK with this as well

**Comment by taotetek** [comment]
Finished this work.
