### ISSUE TITLE
Problem: some socket options should accept []byte, not string

### ISSUE THREAD

**Issue by PSG-Luna** [zeromq/goczmq#90]
Socket options such as the curve pub/private keys currently accept strings, these should accept byte buffers instead

Additionally, some boolean options currently accept an int, those should be changed to bools

**Comment by taotetek** [comment]
@PSG-Luna Hey Luna - do we care about this issue any more?  If so I'll gladly leave it open, just can't remember what this impacts.

**Comment by taotetek** [comment]
I'm going to close this - if it returns as something that is causing a real problem that needs fixing someone can submit a PR.
