### ISSUE TITLE
Sometimes, go test will stacktrace (very rarely)

### ISSUE THREAD

**Issue by PSG-Luna** [zeromq/goczmq#94]
panic: close of closed channel

goroutine 4 [running]:
github.com/zeromq/goczmq.func·001(0xc2080286c0)
        /home/luna/src/delta-go-workspace/src/github.com/zeromq/goczmq/channeler.go:54 +0x2c

goroutine 1 [chan receive]:
testing.RunTests(0x5d2e60, 0x84e7e0, 0x3f, 0x3f, 0xf12e18507a1cb101)
        /usr/lib/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20802c0a0, 0x869280)
        /usr/lib/go/src/testing/testing.go:485 +0x6c
main.main()
        github.com/zeromq/goczmq/_test/_testmain.go:176 +0x1d5

goroutine 64 [syscall, locked to thread]:
github.com/zeromq/goczmq._Cfunc_zsock_destroy_(0xc208038450, 0x7f3190002240, 0x97)
        github.com/zeromq/goczmq/_test/_obj_test/_cgo_gotypes.go:339 +0x45
github.com/zeromq/goczmq.(*Sock).Destroy(0xc208038450)
        /home/luna/src/delta-go-workspace/src/github.com/zeromq/goczmq/sock.go:341 +0x61
github.com/zeromq/goczmq.TestREQREP(0xc20808a000)
        /home/luna/src/delta-go-workspace/src/github.com/zeromq/goczmq/sock_test.go:232 +0xaf3
testing.tRunner(0xc20808a000, 0x84ed08)
        /usr/lib/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
        /usr/lib/go/src/testing/testing.go:555 +0xa8b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
FAIL    github.com/zeromq/goczmq        0.757s

**Comment by taotetek** [comment]
Fixed by https://github.com/zeromq/goczmq/pull/111
